name: Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - run: yarn install
      - run: yarn build
      - run: yarn test
        env:
          # to solve problem of memory leak https://stackoverflow.com/a/59572966
          NODE_OPTIONS: "--max-old-space-size=4096"

  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - run: yarn install
      - run: yarn build
      - run: yarn bench
        env:
          # to solve problem of memory leak https://stackoverflow.com/a/59572966
          NODE_OPTIONS: "--max-old-space-size=4096"

  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - run: yarn install
      - run: yarn build
      - run: npx hardhat deploy

  build-zksync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - run: yarn install
      - run: yarn build-zksync
        env:
          TESTNET_PRIVATE_KEY: '0000000000000000000000000000000000000000000000000000000000000000'

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - run: yarn install
      - run: yarn build
      - run: yarn coverage
        env:
          # to solve problem of memory leak https://stackoverflow.com/a/59572966
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - run: yarn install
      - run: yarn lint
